name: vos
channels:
- pytorch
dependencies:
- python=3.6
- cudatoolkit=10.
- numpy
- psutil
- pillow==6.2.2
- pip
- pip:
  - scikit-image
  - pycocotools
  - torch==1.0.1.post2
  - torchvision==0.2.2.post2
  - opencv-python # It is recommended to install manually
  - matplotlib
  - graphviz
  - tqdm
  - jupyter # visualy debug
  - ptvsd # vscode debug
  # - git+git://github.com/ziwenzhuang/exptools@add_tensorboard # the tools to manage experiment